name: MSBuild
on: [push]
jobs:
  build:
    runs-on: [MSBuild]
    steps:
      - name: Set up JDK
        uses: actions/setup-java@v3.5.1
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
