name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
          matrix:
            configuration: [Release]

    runs-on: self-hosted

    env:
          Solution_Name: ..\ClassLibraryMSBuild\ClassLibraryMSBuild.csproj

    steps:
    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore the application
      run: msbuild $env:Solution_Name /t:Restore
    - name: Build app
      run: msbuild $env:Solution_Name /p:Configuration=$env:Configuration
